site_name: Mes Documentations
#site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  custom_dir: overrides
  logo: img/lexii-io-icon.png
  favicon: img/lexii-io-icon.png
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    #- navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: light blue
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jipjab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/daddydy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mutuyimana
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="#"  target="_blank" rel="noopener">JiPJaB</a>

nav:
    - Home: 'index.md'
    - 'Tips & Tricks': 'Tricks.md'
    - 'Minimum Security Settings': 'SecurityProcesses.md'
    - 'PKI': 'certs.md'
    - Controles CIS:
        - 'M365/AAD': 'Controles-CIS.md'
    - Microsoft:
        - 'Az. Security Best Practices': 'Azure.md'
        - 'Windows Group Policies': 'GPOs.md'
        - 'SharePoint': 'SharePoint.md'
        - 'Intune': 'Intune.md'
        - 'Defender for EndPoint': 'MDE.md'
        - 'kql': 'kql.md'
    - Commands:
        - 'Standard': 'commands.md'
        - 'Scripts-Checks': 'FileCheck.md'
        - 'Powershell' : 'powershell.md'
    - Cybereason: 'Cybereason.md'